// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddGroup: typeof import('./components/AddGroup.vue')['default']
    GroupView: typeof import('./components/GroupView.vue')['default']
    Person: typeof import('./components/Person.vue')['default']
    Persons: typeof import('./components/Persons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
